### ISSUE TITLE
Exception when trying to use WATCHMODE_WATCHEDBEFORE

### ISSUE THREAD

**Issue by paradox00** [rmrector/script.playrandomvideos#11]
```
2022-04-08 17:36:19.923 T:30176   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name '_build_watched_before_fiter' is not defined
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.playrandomvideos/python/context.py", line 14, in <module>
                                                       playrandom.play(pathinfo)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.playrandomvideos/python/lib/playrandom.py", line 32, in play
                                                       content, info = _parse_path(pathinfo)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.playrandomvideos/python/lib/playrandom.py", line 151, in _parse_path
                                                       lastwatched_filter = _build_watched_before_fiter(content)
                                                   NameError: name '_build_watched_before_fiter' is not defined
                                                   -->End of Python script error report<--
```
Probably bad merge with 65a8efa8ffa742096f903837ccfe2801d63dd2cf.

**Comment by rmrector** [comment]
Recently fixed and merged and pushed to the Kodi add-on repo.
